spring:
  config:
    import: optional:application-local.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ongidb?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    generate-ddl: true
#    show-sql: true
    properties:
      format_sql: true
  logging:
    level:
      org.springframework.web: DEBUG

jwt:
  secret: ${JWT_SECRET_KEY}

coolsms:
  api:
    key: ${SMS_KEY}
    secret: ${SMS_SECRET}
    number: ${SMS_NUMBER}