server:
  forward-headers-strategy: framework

spring:
  config:
    import: optional:application-local.yml
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}:3306/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&sessionVariables=time_zone='Asia/Seoul'
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    properties:
      format_sql: true

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket : ${S3_BUCKET_NAME}

  jackson:
    time-zone: Asia/Seoul

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.boot.context.config: DEBUG
    org.springframework.core.env: DEBUG
    com.google.firebase: debug
    com.google.api.client: debug
    com.solution.Ongi: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info
    health:
      probes:
        enabled: true

jwt:
  secret: ${JWT_SECRET_KEY}

coolsms:
  api:
    key: ${SMS_KEY}
    secret: ${SMS_SECRET}
    number: ${SMS_NUMBER}

firebase:
  service-account-file: ${FIREBASE_SERVICE_ACCOUNT_PATH}

