name: Deploy to EC2

on:
  workflow_run:
    workflows:
      - "Build and Push to ECR"
    types:
      - "completed"

jobs:
  deploy:
    name: SSH and Deploy to EC2
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.6
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            REGION="ap-northeast-2"
            ECR_REGISTRY=${{ secrets.ECR_REGISTRY }}
            ECR_REPOSITORY=${{ secrets.ECR_REPOSITORY }}
            IMAGE_TAG=${{ github.sha }}
            AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}

            docker stop ongi-server || true
            docker rm ongi-server || true

            aws ecr get-login-password --region $REGION \
              | docker login --username AWS --password-stdin \
              $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
            docker pull \
              $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

            docker run -d \
              --name ongi-server \
              -p 8080:8080 \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e DB_NAME="${{ secrets.DB_NAME }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e DB_URL="${{ secrets.DB_URL }}" \
              -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
              -e FIREBASE_SERVICE_ACCOUNT_PATH="${{ secrets.FIREBASE_SERVICE_ACCOUNT_PATH }}" \
              -e JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" \
              -e SMS_KEY="${{ secrets.SMS_KEY }}" \
              -e SMS_NUMBER="${{ secrets.SMS_NUMBER }}" \
              -e SMS_SECRET="${{ secrets.SMS_SECRET }}" \
              -e AWS_ACCESS_KEY="${{ secrets.AWS_IAM_ACCESS_KEY_ID }}" \
              -e AWS_SECRET_KEY="${{ secrets.AWS_IAM_SECRET_ACCESS_KEY }}" \
              -e S3_BUCKET="${{ secrets.S3_BUCKET }}" \
              $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPOSITORY
